name: Test ROS 2 Jazzy Packages

on:
  push:
    branches:
      - jazzy*
  pull_request:
    branches:
      - jazzy*

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup ROS 2 Jazzy
      uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: jazzy

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y python3-colcon-common-extensions

    - name: Clone Dependencies
      run: |
        mkdir -p ~/workspace/src
        cd ~/workspace/src
        git clone https://github.com/DHBW-Smart-Rollerz/camera_preprocessing.git
        git clone https://github.com/DHBW-Smart-Rollerz/smarty_utils.git
        cd ..
        rosdep init
        rosdep update
        rosdep install --from-paths src --ignore-src --rosdistro jazzy -y

    - name: Build packages
      run: |
        colcon build --event-handlers console_cohesion+

    - name: Run tests
      run: |
        colcon test --event-handlers console_cohesion+
        colcon test-result --verbose

    - name: Finish
      run: echo "Build and test finished"
